config/routes.rb
Rails.application.routes.draw do
  # get 'pockets/demo'
  # get 'pockets/index'
  # get 'payments/demo'
  # get 'payments/index'
  # get 'reports/demo'
  # get 'reports/index'
  # get 'exams/demo'
  # get 'exams/index'
  # get 'teachers/demo'
  # get 'teachers/index'
  # get 'students/demo'
  # get 'students/index'

  resources :students
  resources :teachers
  resources :exams
  resources :reports
  resources :pockets
  resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new #untuk menampilkan form data baru
    @teacher = Teacher.new
  end

  def create #untuk memproses data baru yang dimasukkan di form new
    teacher = Teacher.new(resource_params)
    teacher.save
    flash[:notice] = 'Teacher has been created'
    redirect_to teachers_path 
  end

  def edit #menampilkan data yang sudah disimpan diedit
    id = params[:id]
    @teachers = Teacher.find(id)
    
  end

  def update #melakukan proses ketika user mengedit data
    id = params[:id]
    @teacher = Teacher.find(params[:id])
    @teacher.update(resource_params)
    flash[:notice] = 'Teacher has been update'
    redirect_to teachers_path(@teacher)
  end

  def destroy #untuk menghapus data
    id = params[:id]
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    flash[:notice] = 'Teacher has been deleted'
    redirect_to teachers_path(@teacher)
  end

  def index #menampilkan seluruh data yang ada di database
    @teachers = Teacher.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @teacher = Teacher.find(id)
    # render plain:id
    # render plain: @book.title
  end

  def resource_params
    params.require(:teacher).permit(:nik, :name, :age, :kelas, :mapel)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<%= form_for @teachers do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>
    
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>
    
    <%= f.submit "Save" %>

<% end %>

app/views/teachers/index.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> </br>
<table>
  <tr>
      <td>NIK</td>
      <td>Name</td>
      <td>Age</td>
      <td>Kelas</td>
      <td>Mapel</td>

  </tr>
  <% @teachers.each do |teacher| %>
  <tr>
     <td><%= teacher.nik %></td>
     <td><%= teacher.name %></td>
     <td><%= teacher.age %></td>
     <td><%= teacher.kelas %></td>
     <td><%= teacher.mapel %></td>
     <td><%= link_to 'Detail', teacher_path(teacher) %>| <%= link_to 'Edit', edit_teacher_path(teacher) %> | <%= link_to 'Delete', teacher_path(teacher), method: :delete, data: {confirm: 'Are you sure?'} %></td> 
    </tr>
  <% end %>
</table>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<%= form_for @teacher do |f| %>
    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>
    
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.submit "Save" %>

<% end %>

app/views/teachers/show.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> </br>

NIK : <%= @teacher.nik %> </br>
Name : <%= @teacher.name %> </br>
Age : <%= @teacher.age %> </br>
Kelas : <%= @teacher.kelas %> </br>
Mapel : <%= @teacher.mapel %> </br>