config/routes.rb
Rails.application.routes.draw do
  # get 'pockets/demo'
  # get 'pockets/index'
  # get 'payments/demo'
  # get 'payments/index'
  # get 'reports/demo'
  # get 'reports/index'
  # get 'exams/demo'
  # get 'exams/index'
  # get 'teachers/demo'
  # get 'teachers/index'
  # get 'students/demo'
  # get 'students/index'

  resources :students
  resources :teachers
  resources :exams
  resources :reports
  resources :pockets
  resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new #untuk menampilkan form data baru
    @payment = Payment.new
  end

  def create #untuk memproses data baru yang dimasukkan di form new
    payment = Payment.new(resource_params)
    payment.save
    flash[:notice] = 'Payment has been created'
    redirect_to payments_path 
  end

  def edit #menampilkan data yang sudah disimpan diedit
    id = params[:id]
    @payments = Payment.find(id)
    
  end

  def update #melakukan proses ketika user mengedit data
    id = params[:id]
    @payment = Payment.find(params[:id])
    @payment.update(resource_params)
    flash[:notice] = 'Payment has been update'
    redirect_to payments_path(@teacher)
  end

  def destroy #untuk menghapus data
    id = params[:id]
    @payment = Payment.find(params[:id])
    @payment.destroy
    flash[:notice] = 'Teacher has been deleted'
    redirect_to payments_path(@payment)
  end

  def index #menampilkan seluruh data yang ada di database
    @payments = Payment.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @payment = Payment.find(id)
    # render plain:id
    # render plain: @book.title
  end

  def resource_params
    params.require(:payment).permit(:id_transaction, :status, :upload)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/edit.html.erb
<%= form_for @payments do |f| %>
    <%= f.label :id_transaction %> </br>
    <%= f.text_field :id_transaction %> </br>
    
    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload %> </br>
    
    <%= f.submit "Save" %>

<% end %>

app/views/payments/index.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> </br>
<table>
  <tr>
      <td>ID Transaction</td>
      <td>Status</td>
      <td>Upload</td>

  </tr>
  <% @payments.each do |payment| %>
  <tr>
     <td><%= payment.id_transaction %></td>
     <td><%= payment.status %></td>
     <td><%= payment.upload %></td>
     <td><%= link_to 'Detail', payment_path(payment) %>| <%= link_to 'Edit', edit_payment_path(payment) %> | <%= link_to 'Delete', payment_path(payment), method: :delete, data: {confirm: 'Are you sure?'} %></td> 
    </tr>
  <% end %>
</table>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<%= form_for @payment do |f| %>
    <%= f.label :id_transaction %> </br>
    <%= f.text_field :id_transaction %> </br>
    
    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :upload %> </br>
    <%= f.text_field :upload %> </br>

    <%= f.submit "Save" %>

<% end %>

app/views/payments/show.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> </br>

ID Transaction : <%= @payment.id_transaction %> </br>
Status : <%= @payment.status %> </br>
Upload : <%= @payment.upload %> </br>