config/routes.rb
Rails.application.routes.draw do
  # get 'pockets/demo'
  # get 'pockets/index'
  # get 'payments/demo'
  # get 'payments/index'
  # get 'reports/demo'
  # get 'reports/index'
  # get 'exams/demo'
  # get 'exams/index'
  # get 'teachers/demo'
  # get 'teachers/index'
  # get 'students/demo'
  # get 'students/index'

  resources :students
  resources :teachers
  resources :exams
  resources :reports
  resources :pockets
  resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new #untuk menampilkan form data baru
    @exam = Exam.new
  end

  def create #untuk memproses data baru yang dimasukkan di form new
    exam = Exam.new(resource_params)
    exam.save
    flash[:notice] = 'Exam has been created'
    redirect_to exams_path 
  end

  def edit #menampilkan data yang sudah disimpan diedit
    id = params[:id]
    @exams = Exam.find(id)
    
  end

  def update #melakukan proses ketika user mengedit data
    id = params[:id]
    @exam = Exam.find(params[:id])
    @exam.update(resource_params)
    flash[:notice] = 'Exam has been update'
    redirect_to exams_path(@exam)
  end

  def destroy #untuk menghapus data
    id = params[:id]
    @exam = Exam.find(params[:id])
    @exam.destroy
    flash[:notice] = 'Exam has been deleted'
    redirect_to exams_path(@exam)
  end

  def index #menampilkan seluruh data yang ada di database
    @exams = Exam.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @exam = Exam.find(id)
    # render plain:id
    # render plain: @book.title
  end
private
  def resource_params
    params.require(:exam).permit(:title, :mapel, :duration, :nilai, :status, :level, :student_id)
  end

end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/edit.html.erb
<%= form_for @exams do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>
    
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>
    
    <%= f.submit "Save" %>

<% end %>

app/views/exams/index.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> </br>
<table>
  <tr>
      <td>Title</td>
      <td>Mapel</td>
      <td>Duration</td>
      <td>Nilai</td>
      <td>Status</td>
      <td>Level</td>
      <td>Student ID</td>

  </tr>
  <% @exams.each do |exam| %>
  <tr>
     <td><%= exam.title %></td>
     <td><%= exam.mapel %></td>
     <td><%= exam.duration %></td>
     <td><%= exam.nilai %></td>
     <td><%= exam.status %></td>
     <td><%= exam.level %></td>
     <td><%= exam.student_id %></td>
     <td><%= link_to 'Detail', exam_path(exam) %>| <%= link_to 'Edit', edit_exam_path(exam) %> | <%= link_to 'Delete', exam_path(exam), method: :delete, data: {confirm: 'Are you sure?'} %></td> 
    </tr>
  <% end %>
</table>

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/new.html.erb
<%= form_for @exam do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>
    
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.submit "Save" %>

<% end %>

app/views/exams/show.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> </br>

Title : <%= @exam.title %> </br>
Mapel : <%= @exam.mapel %> </br>
Duration : <%= @exam.duration %> </br>
Nilai : <%= @exam.nilai %> </br>
Status : <%= @exam.status %> </br>
Level : <%= @exam.level %> </br>
Student ID : <%= @exam.student_id %> </br>