config/routes.rb
Rails.application.routes.draw do
  # get 'pockets/demo'
  # get 'pockets/index'
  # get 'payments/demo'
  # get 'payments/index'
  # get 'reports/demo'
  # get 'reports/index'
  # get 'exams/demo'
  # get 'exams/index'
  # get 'teachers/demo'
  # get 'teachers/index'
  # get 'students/demo'
  # get 'students/index'

  resources :students
  resources :teachers
  resources :exams
  resources :reports
  resources :pockets
  resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new #untuk menampilkan form data baru
    @report = Report.new
  end

  def create #untuk memproses data baru yang dimasukkan di form new
    report = Report.new(resource_params)
    report.save
    flash[:notice] = 'Report has been created'
    redirect_to reports_path 
  end

  def edit #menampilkan data yang sudah disimpan diedit
    id = params[:id]
    @reports = Report.find(id)
    
  end

  def update #melakukan proses ketika user mengedit data
    id = params[:id]
    @report = Report.find(params[:id])
    @report.update(resource_params)
    flash[:notice] = 'Report has been update'
    redirect_to reports_path(@report)
  end

  def destroy #untuk menghapus data
    id = params[:id]
    @report = Report.find(params[:id])
    @report.destroy
    flash[:notice] = 'Report has been deleted'
    redirect_to reports_path(@report)
  end

  def index #menampilkan seluruh data yang ada di database
    @reports = Report.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @report = Report.find(id)
    # render plain:id
    # render plain: @book.title
  end

  def resource_params
    params.require(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id, :date)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/edit.html.erb
<%= form_for @reports do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>
    
    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :date %> </br>
    <%= f.text_field :date %> </br>
    
    <%= f.submit "Save" %>

<% end %>

app/views/reports/index.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> </br>
<table>
  <tr>
      <td>Title</td>
      <td>Hasil</td>
      <td>Mapel</td>
      <td>Teacher ID</td>
      <td>Student ID</td>
      <td>Date</td>

  </tr>
  <% @reports.each do |report| %>
  <tr>
     <td><%= report.title %></td>
     <td><%= report.hasil %></td>
     <td><%= report.mapel %></td>
     <td><%= report.teacher_id %></td>
     <td><%= report.student_id %></td>
     <td><%= report.date %></td>
     <td><%= link_to 'Detail', report_path(report) %>| <%= link_to 'Edit', edit_report_path(report) %> | <%= link_to 'Delete', report_path(report), method: :delete, data: {confirm: 'Are you sure?'} %></td> 
    </tr>
  <% end %>
</table>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<%= form_for @report do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>
    
    <%= f.label :hasil %> </br>
    <%= f.text_field :hasil %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :teacher_id %> </br>
    <%= f.text_field :teacher_id %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.label :date %> </br>
    <%= f.text_field :date %> </br>

    <%= f.submit "Save" %>

<% end %>

app/views/reports/show.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> </br>

Title : <%= @report.title %> </br>
Hasil : <%= @report.hasil %> </br>
Mapel : <%= @report.mapel %> </br>
Teacher ID : <%= @report.teacher_id %> </br>
Student ID : <%= @report.student_id %> </br>
Date : <%= @report.date %> </br>